services:
    kernel.listener.access_denied.handler:
        class: DesportoBundle\DependencyInjection\AccessDeniedHandler
        arguments: ["@session", "@router"]
        tags:
           - { name: kernel.event_listener, event: security.kernel_response, method: handle}
