services:
    kernel.listener.access_denied.handler:
        class: DesportoBundle\DependencyInjection\AccessDeniedHandler
        arguments: ["@session", "@router"]
        tags:
           - { name: kernel.event_listener, event: security.kernel_response, method: handle}
    upload:
        class:  DesportoBundle\Service\UploadService
        arguments: ["@request_stack"]
    profissional:
        class:  DesportoBundle\Service\ProfissionalService
        arguments: ["@request_stack", "@kernel", "@upload", "@doctrine.orm.entity_manager" ]
    equipe:
        class:  DesportoBundle\Service\EquipeService
        arguments: ["@request_stack", "@kernel", "@upload", "@doctrine.orm.entity_manager" ]
    edicao_campeonato:
        class:  DesportoBundle\Service\EdicaoCampeonatoService
        arguments: ["@doctrine.orm.entity_manager" ]
        
    desporto.form.profissional:
        class: DesportoBundle\Form\ProfissionalType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }
    desporto.form.equipe:
        class: DesportoBundle\Form\EquipeType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }
    desporto.form.edicaoCampeonato:
        class: DesportoBundle\Form\EdicaoCampeonatoType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }
    desporto.form.chave:
        class: DesportoBundle\Form\ChaveType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }
    desporto.form.faseClassificatoria:
        class: DesportoBundle\Form\FaseClassificatoriaType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }
    desporto.form.type.entity_hidden:
        class: DesportoBundle\Form\Type\EntityHiddenType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
        - { name: form.type, alias: entity_hidden }
