version: "2.1"
volumes:
  mysql:
services:
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    ports:
      - "${VIRTUAL_MYSQL_PORT:-3306}:3306"
    volumes:
      - mysql:/var/lib/mysql
  php:
    build: ./docker/php
    volumes:
      - ${DESPORTO_DIR:-./}:/var/www/html
    links:
      - mysql:desporto-mysql
  nginx:
    build: ./docker/nginx
    volumes:
      - ${DESPORTO_DIR:-./}:/var/www/html
    links:
      - php:desporto-php
    ports:
      - "${DESPORTO_NGINX_PORT:-80}:80"
    depends_on:
      - mysql
